keys:
  - &testkeys age17jm37tskyl32d328yude9dz5l8te892d6df4hnchuknh2dn06glq2dfrss
  - &nextcloud age1vd9szene8tx975ujck0fxmvycqaj5z3tslt94ukr0hc5v3latg8s4ehwaz
  - &test2 age1vxvytx0lgd3ksmskvhnfgy4qgw66urkk65z3h4hdpaxlm4qt7gds05leay
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *test2
      - *testkeys
      - *nextcloud