{ config, lib, pkgs, ... }:
{
  imports = [
    ./app-notifications-css.nix
    ./assistant-css.nix
    ./button-css.nix
    ./calendar-css.nix
    ./cell-row-css.nix
    ./check-radio-css.nix
    ./color-chooser-css.nix
    ./column-header-css.nix
    ./combobox-css.nix
    ./content-view-css.nix
    ./csd-css.nix
    ./dialogs-css.nix
    ./entry-css.nix
    ./gnome-sofware-css.nix
    ./infobar-css.nix
    ./list-boxes-css.nix
    ./menu-css.nix
    ./notebook-css.nix
    ./osd-css.nix
    ./popover-css.nix
    ./progress-scale-css.nix
    ./scrollbar-css.nix
    ./search-bar-css.nix
    ./selection-mode-css.nix
    ./separator-css.nix
    ./sidebar-css.nix
    ./spinbutton-css.nix
    ./spinner-css.nix
    ./switch-css.nix
    ./toolbar-css.nix
  ];
}