on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: ["**"]

name: Test on Arch-Linux
jobs:
  test-arch-release:
    runs-on: ubuntu-latest
    container: archlinux
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "pacman --noconfirm -Syu base-devel cmake gcc git make pipewire pipewire-pulse"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Drohrkabel_examples=ON && cmake --build . --config Release"

  test-arch-debug:
    runs-on: ubuntu-latest
    container: archlinux
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "pacman --noconfirm -Syu base-devel cmake gcc git make pipewire pipewire-pulse wireplumber"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Drohrkabel_examples=ON && cmake --build . --config Debug"
