on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: ["**"]

name: Test on Ubuntu
jobs:
  test-ubuntu-focal-release:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Add PPA
        run: "sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream"

      - name: Install build dependencies
        run: "sudo apt-get update && sudo apt-get install git build-essential cmake pipewire libpipewire-0.3-0 libpipewire-0.3-dev pipewire-pulse"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Drohrkabel_examples=ON && cmake --build . --config Release"

  test-ubuntu-focal-debug:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Add PPA
        run: "sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream"

      - name: Install build dependencies
        run: "sudo apt-get update && sudo apt-get install git build-essential cmake pipewire libpipewire-0.3-0 libpipewire-0.3-dev pipewire-pulse"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Drohrkabel_examples=ON && cmake --build . --config Debug"

  test-ubuntu-jammy-release:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "sudo apt-get update && sudo apt-get install git build-essential cmake wireplumber pipewire libpipewire-0.3-0 libpipewire-0.3-dev pipewire-pulse"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Drohrkabel_examples=ON && cmake --build . --config Release"

  test-ubuntu-jammy-debug:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "sudo apt-get update && sudo apt-get install git build-essential cmake  wireplumber pipewire libpipewire-0.3-0 libpipewire-0.3-dev pipewire-pulse"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Drohrkabel_examples=ON && cmake --build . --config Debug"
